export const monitorItems = [
  {
    id: 1,
    title: 'Uptime Monitoring',
    color: 'bg-[#FFD600]',
    text: 'INTERNET',
    detail: 'Track your website availability 24/7 with zero blind spots.',
    x: '8%',
    y: '35%',
    size: { w: 'clamp(180px, 23vw, 280px)', h: 'clamp(150px, 18vw, 200px)' },
    mobile: { w: '40vw', h: '136px', x: '5%', y: '22%' },
  },
  {
    id: 2,
    title: 'Latency Tracking',
    color: 'bg-[#00E676]',
    text: 'MS_TRACK',
    detail: 'Measure response times and detect slowdowns instantly.',
    x: '63%',
    y: '14%',
    size: { w: 'clamp(165px, 17vw, 200px)', h: 'clamp(140px, 15vw, 170px)' },
    mobile: { w: '36vw', h: '126px', x: '57%', y: '18%' },
  },
  {
    id: 3,
    title: 'Real-Time Alerts',
    color: 'bg-[#FF4D4D]',
    text: 'PREDICTIVE',
    detail: 'Get notified the moment something breaks.',
    x: '28%',
    y: '48%',
    size: { w: 'clamp(165px, 17vw, 200px)', h: 'clamp(150px, 18vw, 200px)' },
    mobile: { w: '37vw', h: '136px', x: '7%', y: '42%' },
  },
  {
    id: 4,
    title: 'Dashboards and Logs',
    color: 'bg-[#FF4D4D]',
    text: 'NET_LOGS',
    detail: 'Visualize performance and debug issues faster.',
    x: '68%',
    y: '38%',
    size: { w: 'clamp(160px, 16vw, 190px)', h: 'clamp(145px, 17vw, 190px)' },
    mobile: { w: '38vw', h: '132px', x: '55%', y: '41%' },
  },
  {
    id: 5,
    title: 'AI Incident Summaries',
    color: 'bg-[#FFD600]',
    text: 'OF THINGS',
    detail: 'Turn errors into clear, actionable insights automatically.',
    x: '45%',
    y: '66%',
    size: { w: 'clamp(220px, 27vw, 320px)', h: 'clamp(125px, 12vw, 140px)' },
    mobile: { w: '78vw', h: '116px', x: '11%', y: '62%' },
  },
  {
    id: 6,
    title: 'API Monitoring',
    color: 'bg-white',
    text: 'SYNC_v4',
    detail: 'Continuously test and validate your API endpoints.',
    x: '43%',
    y: '38%',
    size: { w: 'clamp(170px, 18vw, 220px)', h: 'clamp(120px, 12vw, 140px)' },
    mobile: { w: '36vw', h: '116px', x: '31%', y: '31%' },
  },
  {
    id: 7,
    title: 'Multi-Location Checks',
    color: 'bg-[#00E676]',
    text: 'GLOBAL_NET',
    detail: 'Monitor from different regions for accurate status.',
    x: '72%',
    y: '62%',
    size: { w: 'clamp(165px, 18vw, 230px)', h: 'clamp(125px, 13vw, 150px)' },
    mobile: { w: '38vw', h: '122px', x: '55%', y: '78%' },
  },
  {
    id: 8,
    title: 'Secure Monitoring',
    color: 'bg-white',
    text: 'ENCRYPTED',
    detail: 'Keep your data safe with reliable infrastructure.',
    x: '5%',
    y: '65%',
    size: { w: 'clamp(170px, 18vw, 210px)', h: 'clamp(120px, 12vw, 140px)' },
    mobile: { w: '38vw', h: '122px', x: '7%', y: '78%' },
  },
];

export const howItWorksContent = {
  eyebrow: 'SYSTEM FLOW',
  title: 'How It Works',
  steps: [
    {
      id: 'connect',
      label: '01',
      title: 'Connect Targets',
      copy: 'Add websites, APIs, and critical paths that need constant checks.',
      metric: 'URL/API',
    },
    {
      id: 'probe',
      label: '02',
      title: 'Run Global Checks',
      copy: 'Regional probes watch uptime, latency, and response health in real time.',
      metric: '24/7',
    },
    {
      id: 'alert',
      label: '03',
      title: 'Detect Incidents',
      copy: 'Failures are grouped, scored, and pushed into the alert pipeline fast.',
      metric: 'LIVE',
    },
    {
      id: 'resolve',
      label: '04',
      title: 'Resolve With Context',
      copy: 'Dashboards, logs, and AI summaries turn noise into clear next actions.',
      metric: 'FIX',
    },
  ],
};
